additionalRepositories:
  - url: https://github.com/CP4DModelOps/mlops-churn-api
    checkoutLocation: mlops-churn-api

workspaceLocation: mlops-churn-ui/main.code-workspace

tasks:
  - name: postgresql
    before: cd /home/gitpod/.local/bin
    init: |
      wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz
      tar -xvf oc.tar.gz
      rm README.md oc.tar.gz
      oc login --token=$OCP_TOKEN --server=$OCP_SERVER
      oc project $OCP_PROJECT
    command: oc port-forward pg-postgresql-0 5432:5432
  - name: mlops-churn-api
    before: cd ../mlops-churn-api
    init: |
      npm install
      npm run build
    command: npm run start
  - name: mlops-churn-ui
    init: yarn install
    command: yarn start:dev