additionalRepositories:
  - url: https://github.com/CP4DModelOps/mlops-churn-api
    checkoutLocation: mlops-churn-api

workspaceLocation: ascent-ui/main.code-workspace

tasks:
  - name: mlops-churn-api
    before: cd ../mlops-churn-api
    init: |
      npm install
      npm run build
    command: npm run start
  - name: mlops-churn-ui
    init: yarn install
    command: yarn start:dev
